/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecomendarRouteImport } from './routes/recomendar'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CastilloSlugRouteImport } from './routes/castillo.$slug'

const RecomendarRoute = RecomendarRouteImport.update({
  id: '/recomendar',
  path: '/recomendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CastilloSlugRoute = CastilloSlugRouteImport.update({
  id: '/castillo/$slug',
  path: '/castillo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/mapa': typeof MapaRoute
  '/recomendar': typeof RecomendarRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/mapa': typeof MapaRoute
  '/recomendar': typeof RecomendarRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/mapa': typeof MapaRoute
  '/recomendar': typeof RecomendarRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/mapa'
    | '/recomendar'
    | '/castillo/$slug'
    | '/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/mapa'
    | '/recomendar'
    | '/castillo/$slug'
    | '/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/mapa'
    | '/recomendar'
    | '/castillo/$slug'
    | '/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  MapaRoute: typeof MapaRoute
  RecomendarRoute: typeof RecomendarRoute
  CastilloSlugRoute: typeof CastilloSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recomendar': {
      id: '/recomendar'
      path: '/recomendar'
      fullPath: '/recomendar'
      preLoaderRoute: typeof RecomendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castillo/$slug': {
      id: '/castillo/$slug'
      path: '/castillo/$slug'
      fullPath: '/castillo/$slug'
      preLoaderRoute: typeof CastilloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  MapaRoute: MapaRoute,
  RecomendarRoute: RecomendarRoute,
  CastilloSlugRoute: CastilloSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
