/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecomendarRouteImport } from './routes/recomendar'
import { Route as RankingCastillosRouteImport } from './routes/ranking-castillos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CastilloSlugRouteImport } from './routes/castillo.$slug'
import { Route as ApiPublicVisitaRouteImport } from './routes/api/public/visita'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendarRoute = RecomendarRouteImport.update({
  id: '/recomendar',
  path: '/recomendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingCastillosRoute = RankingCastillosRouteImport.update({
  id: '/ranking-castillos',
  path: '/ranking-castillos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CastilloSlugRoute = CastilloSlugRouteImport.update({
  id: '/castillo/$slug',
  path: '/castillo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitaRoute = ApiPublicVisitaRouteImport.update({
  id: '/api/public/visita',
  path: '/api/public/visita',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/ranking-castillos': typeof RankingCastillosRoute
  '/recomendar': typeof RecomendarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/api/public/visita': typeof ApiPublicVisitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/ranking-castillos': typeof RankingCastillosRoute
  '/recomendar': typeof RecomendarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/api/public/visita': typeof ApiPublicVisitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/ranking-castillos': typeof RankingCastillosRoute
  '/recomendar': typeof RecomendarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/castillo/$slug': typeof CastilloSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/api/public/visita': typeof ApiPublicVisitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/mapa'
    | '/ranking-castillos'
    | '/recomendar'
    | '/sitemap.xml'
    | '/castillo/$slug'
    | '/categoria/$slug'
    | '/api/public/visita'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/mapa'
    | '/ranking-castillos'
    | '/recomendar'
    | '/sitemap.xml'
    | '/castillo/$slug'
    | '/categoria/$slug'
    | '/api/public/visita'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/mapa'
    | '/ranking-castillos'
    | '/recomendar'
    | '/sitemap.xml'
    | '/castillo/$slug'
    | '/categoria/$slug'
    | '/api/public/visita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  FavoritosRoute: typeof FavoritosRoute
  MapaRoute: typeof MapaRoute
  RankingCastillosRoute: typeof RankingCastillosRoute
  RecomendarRoute: typeof RecomendarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CastilloSlugRoute: typeof CastilloSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ApiPublicVisitaRoute: typeof ApiPublicVisitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendar': {
      id: '/recomendar'
      path: '/recomendar'
      fullPath: '/recomendar'
      preLoaderRoute: typeof RecomendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-castillos': {
      id: '/ranking-castillos'
      path: '/ranking-castillos'
      fullPath: '/ranking-castillos'
      preLoaderRoute: typeof RankingCastillosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castillo/$slug': {
      id: '/castillo/$slug'
      path: '/castillo/$slug'
      fullPath: '/castillo/$slug'
      preLoaderRoute: typeof CastilloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visita': {
      id: '/api/public/visita'
      path: '/api/public/visita'
      fullPath: '/api/public/visita'
      preLoaderRoute: typeof ApiPublicVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  FavoritosRoute: FavoritosRoute,
  MapaRoute: MapaRoute,
  RankingCastillosRoute: RankingCastillosRoute,
  RecomendarRoute: RecomendarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CastilloSlugRoute: CastilloSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ApiPublicVisitaRoute: ApiPublicVisitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
